# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" , "dev"]
  pull_request:
    branches: [ "main" , "dev"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies (GameOfLife)
      run: dotnet restore
      working-directory: GameOfLife
      
    - name: Build (GameOfLife)
      run: dotnet build --no-restore
      working-directory: GameOfLife
      
    - name: Restore dependencies (GameOfLife.Tests)
      run: dotnet restore
      working-directory: GameOfLife.Tests
      
    - name: Test (GameOfLife.Tests)
      run: dotnet test  
      working-directory: GameOfLife
